version: "3"

services:
  reverseproxy:
    build: ./reverseproxy
    ports:
      - 3000:80
    restart: always

  www:
    build: ./www
    depends_on:
      - reverseproxy
    restart: always

  api:
    build: ./api
    depends_on:
      - reverseproxy
    environment:
      SERVICE_HOST: http://internal:5000
    volumes:
      - storage123:/storage
    restart: always

  internal:
    build: ./internal
    depends_on:
      - reverseproxy
    environment:
      PERSIST_STORAGE: /storage
    volumes:
      - storage123:/storage
    restart: always

volumes:
  storage123:
